Feat(core): Add cypress test

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -229,6 +229,18 @@ jobs:
             echo -e "\033[0;31mPHPUnit binary not found!\033[0m"
             exit 1
           fi
+      - name: "Cypress"
+        if: ${{ !cancelled() && hashFiles(format('{0}/tests/cypress.config.js', inputs.plugin-key)) != '' }}
+        run: |
+          echo -e "\033[0;33mExecuting Cypress...\033[0m"
+          if [[ -f "node_modules/.bin/cypress" ]]; then
+            node_modules/.bin/cypress run --project tests
+          elif [[ -f "../../node_modules/.bin/cypress" ]]; then
+            ../../node_modules/.bin/cypress run --project tests
+          else
+            echo -e "\033[0;31mCypress binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Jest"
         if: ${{ !cancelled() && hashFiles(format('{0}/jest.config.js', inputs.plugin-key)) != '' }}
         run: |
